openapi: 3.0.0
info:
  title: NEM NIS API Endpoints
  version: 1.1.9
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: OpenAPI Specification of NEM NIS API
tags:
  - name: block
  - name: chain
  - name: nis-status
paths:
  /block/at/public:
    post:
      operationId: Block_getBlockAtHeight
      summary: Getting a block with a given height
      description: ''
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema: {}
      tags:
        - block
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                blockHeight:
                  type: object
  /block/get:
    get:
      operationId: Block_getBlockByHash
      summary: Getting a block with a given hash
      description: ''
      parameters:
        - name: blockHash
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema: {}
      tags:
        - block
  /chain/height:
    get:
      operationId: Chain_getChainInfo
      summary: ''
      description: ''
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockHeight'
      tags:
        - chain
  /chain/last-block:
    get:
      operationId: Chain_getChainLastBlock
      summary: Last block of the block chain score
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema: {}
      tags:
        - chain
  /chain/score:
    get:
      operationId: Chain_getChainScore
      summary: Block chain score
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockChainScore'
      tags:
        - chain
  /heartbeat:
    get:
      operationId: System_getHeartbeat
      summary: ''
      description: ''
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NemRequestResult'
      tags:
        - nis-status
  /status:
    get:
      operationId: System_getStatus
      summary: Status
      description: ''
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NemRequestResult'
      tags:
        - nis-status
components:
  schemas:
    BlockChainScore:
      type: object
      required:
        - score
      properties:
        score:
          type: string
          description: The score of the blockchain as a hexadecimal string.
      description: Represents the score of the blockchain.
    BlockHeight:
      type: object
      required:
        - height
      properties:
        height:
          type: integer
          format: int64
          minimum: 1
          description: The height of the block.
      description: Represents the height of a block in the blockchain.
    NemAnnounceResult:
      type: object
      required:
        - transactionHash
      properties:
        transactionHash:
          allOf:
            - $ref: '#/components/schemas/TransactionHash'
          description: The hash object of the transaction.
        innerTransactionHash:
          type: object
          allOf:
            - $ref: '#/components/schemas/TransactionHash'
          nullable: true
          description: The hash object of the inner transaction or null if the transaction is not a multisig transaction.
      allOf:
        - $ref: '#/components/schemas/NemRequestResult'
      description: |-
        Represents the result of announcing a transaction.
        Extends NemRequestResult with transaction hash information.
    NemRequestResult:
      type: object
      required:
        - type
        - code
        - message
      properties:
        type:
          type: number
          enum:
            - 1
            - 2
            - 4
          description: 'The type of the result (1: validation, 2: heart beat, 4: status).'
        code:
          type: integer
          format: int32
          description: The code of the result. Interpretation depends on the type.
        message:
          type: string
          description: A human-readable message describing the result.
      description: Represents the result of a NEM request, typically used for validation or status.
    TransactionHash:
      type: object
      required:
        - data
      properties:
        data:
          type: string
          format: hex
          description: The transaction hash data as a hexadecimal string.
      description: Represents the hash of a transaction.
servers:
  - url: http://localhost:3000
    description: Local development
    variables: {}
